#!/bin/bash
set -e
set -o pipefail

cd "$1"

# total deletions plus total additions. Git attempts to ignore renaming/moving files, but there is a limit.
# please see the readme for more information
TOTAL_CHANGES="$(git-quick-stats detailedGitStats | tail -n 5 | head -n 2 | awk '{sum+=$2} END {print sum}')"

# total lines in the source code, minus any files gitignore'd (this will slightly change the ratio as per defined in the article, but make it more accurate)
TOTAL_LINES="$(cloc --vcs=git . | tail -n 2 | head -n 1 | awk '{print $NF}')"

# calculate the ratio
echo "scale=2 ; $TOTAL_CHANGES / $TOTAL_LINES" | bc | tr '\n' ':1'
echo "$2"
