#!/bin/bash
set -e
set -o pipefail

cd "$1"

# total deletions plus total additions. Git attempts to ignore renaming/moving files, but there is a limit.
# please see the readme for more information
TOTAL_CHANGES="$(git log --no-merges --numstat --oneline | LC_ALL=C grep '^[0-9]*\s[0-9]*\s' | LC_ALL=C awk '{$2=$2};1' | awk '{additions+=$2; deletions+=$1} END {print (additions+deletions)}')"

# total lines in the source code, minus any files gitignore'd
TOTAL_LINES="$(tokei . | tail -n 2 | head -n 1 | awk '{print $NF}')"

# calculate the ratio
echo -n "$2:"
echo "$TOTAL_CHANGES/$TOTAL_LINES" | bc -l
